version: '3'
services:
  airflow-master:
    build:
      context: .
      args:
       - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
       - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    entrypoint: /usr/local/airflow/script/entrypoint_master.sh
    environment:
     - AIRFLOW__CELERY__CELERY_RESULT_BACKEND=db+postgresql://airflow:airflow@db:5432/airflow
     - AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER=s3://data-team-airflow-logs/airflow-master-tester
     - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@db:5432/airflow
    depends_on:
      - db
    ports:
      - "8080:8080"
  airflow-worker:
    build:
      context: .
      args:
       - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
       - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    entrypoint: /usr/local/airflow/script/entrypoint_worker.sh
    environment:
     - AIRFLOW__CELERY__CELERY_RESULT_BACKEND=db+postgresql://airflow:airflow@db:5432/airflow
     - AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER=s3://data-team-airflow-logs/airflow-worker-tester
     - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@db:5432/airflow
     - QUEUES=test_queue
  db:
   image: postgres
   environment:
     - POSTGRES_DB=airflow
     - POSTGRES_USER=airflow
     - POSTGRES_PASSWORD=airflow
